### ISSUE TITLE
Concatenation fails - Sequence contains no elements

### ISSUE THREAD

**Issue by nouteridgegit** [nolanlab/bead-normalization#11]
Hello,

we have following issue:

When having normalized files using

- Normalizer v0.3 
- on Mac 
- using the free Matlab-RE (NormalizerR2013b_MacOSX.zip)

concatenation of these normalized files will fail, when done via HELIOS (run on a 64bit Win7-PC).

Errormessage:

- ‘Sequence contains no elements’

![error_conc](https://cloud.githubusercontent.com/assets/20245524/18991572/b9eeb942-8719-11e6-9602-83e19dd1997c.png)

Since it only occurs after having normalized the files:
Does someone have any idea what this is causing? 
Is this known to be working this way usually or do we need to use another concatenation tool?

Best regards

**Comment by rfinck** [comment]
I don't know the details of how the Fluidigm concatenation works, but the original FCS files created by the CyTOF do have extra metadata outside of the FCS header that gets removed by the Normalizer. Perhaps this error indicates that it can't find some metadata it is looking for.

However, I would suggest concatenating *before* normalizing anyway, not simply to avoid this error but because it avoids any artifacts from extrapolating normalization factors at the beginnings and ends of files. The key here of course is that the files must be concatenated in order for this to make sense. I don't know if you have control over that with the Fluidigm software.

FCS files can also be concatenated in R, or with this Cytobank tool: https://support.cytobank.org/hc/en-us/articles/206336147-FCS-file-concatenation-tool

**Comment by nouteridgegit** [comment]
Hello R,

thank you very much for the explanation, and your proposal how to deal with it.
The Cytobank tool did the job perfectly for us.

From our point of view this is the solution for our issue.

Best regards
